name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  quality:
    name: Code Quality
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Type check
        run: yarn typecheck

      - name: Lint code
        run: yarn lint

      - name: Check formatting
        run: yarn format:check

  test:
    name: Test Suite
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18, 20, 22]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run unit tests
        run: yarn test

      - name: Build library
        run: yarn build

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run browser tests
        run: |
          # Start demo server for browser tests
          yarn demo &
          SERVER_PID=$!

          # Wait for server to start
          sleep 5

          # Run browser tests
          yarn test:browser

          # Clean up server
          kill $SERVER_PID || true

      - name: Upload test artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-node-${{ matrix.node-version }}
          path: |
            test-results/
            tests/browser/screenshots/
          retention-days: 7

  build:
    name: Build Verification
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build library
        run: yarn build

      - name: Check build outputs
        run: |
          test -f dist/index.js || (echo "Missing CommonJS build" && exit 1)
          test -f dist/index.esm.js || (echo "Missing ESM build" && exit 1)
          test -f dist/index.d.ts || (echo "Missing TypeScript declarations" && exit 1)

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist/
          retention-days: 7

  demo:
    name: Demo Verification
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build library
        run: yarn build

      - name: Test demo server
        run: |
          # Start demo server in background
          yarn demo &
          SERVER_PID=$!

          # Wait for server to start
          sleep 5

          # Check if server is responding
          curl -f http://localhost:8000/demo/demo-with-library.html > /dev/null || (echo "Demo server not responding" && exit 1)

          # Clean up
          kill $SERVER_PID

      - name: Run demo browser tests
        run: |
          # Install Playwright browsers
          npx playwright install --with-deps

          # Start demo server in background
          yarn demo &
          SERVER_PID=$!

          # Wait for server to start
          sleep 5

          # Run browser tests
          yarn test:browser

          # Clean up server
          kill $SERVER_PID || true

      - name: Upload demo screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: demo-screenshots
          path: tests/browser/screenshots/
          retention-days: 7
